### ISSUE TITLE
New issues

### ISSUE THREAD

**Issue by Richard5656** [AudioTore/Rthon#1]
So is wasd an essential part of the game?

**Comment by Richard5656** [comment]
I mean without wasd we could still have a game but the game would be less complex

**Comment by AudioTore** [comment]
@Richard5656 Is there a way to type a letter a a4 then the character just teleports there?

**Comment by Richard5656** [comment]
Yeah

**Comment by AudioTore** [comment]
@Richard5656 Try that i have a feeling that will be easier.

**Comment by Richard5656** [comment]
Can you explain a little more though.

**Comment by Richard5656** [comment]
I don't understand what you mean by a4

**Comment by AudioTore** [comment]
a4 is what shows on the map for players to teleport

**Comment by AudioTore** [comment]
for example: They would type a4 to teleport to a certain place

**Comment by Richard5656** [comment]
Oh so like /TP

**Comment by AudioTore** [comment]
Yeah instead of wasd

**Comment by Richard5656** [comment]
That could work but we would need to render a grid along with wasd

**Comment by Richard5656** [comment]
*grid of numbers

**Comment by AudioTore** [comment]
@Richard5656 Yep!

**Comment by Richard5656** [comment]
Are you sure about this?

**Comment by Richard5656** [comment]
@AudioTore it might look off.

**Comment by Richard5656** [comment]
Im looking into your code right now and everything looks organized. Theres even comments everywhere to explain what everything does.

**Comment by Richard5656** [comment]
Well Im going to start programing in the missions.

**Comment by Richard5656** [comment]
Would you be ok if I have all the missions as dictionaries and put those dictionaries into lists?

**Comment by Richard5656** [comment]
Are you ok with a list for the inventory?

**Comment by AudioTore** [comment]
@Richard5656 Sure

**Comment by AudioTore** [comment]
Put all that in the data folder by the way

**Comment by Richard5656** [comment]
Oh ok

**Comment by AudioTore** [comment]
Is it done?

**Comment by Richard5656** [comment]
Yeah sort of.

**Comment by Richard5656** [comment]
Ill upload what I have now. I only created dictionary's and the list I havent actually linked anything together yet.

**Comment by AudioTore** [comment]
Alright

**Comment by Richard5656** [comment]
https://github.com/AudioTore/Rthon/compare/main...Richard5656:patch-1

**Comment by Richard5656** [comment]
Here it is. Im waiting for you to review the code before I write anymore so it doesnt get too complex or unorganized.

**Comment by Richard5656** [comment]
So is the code ok?

**Comment by AudioTore** [comment]
@Richard5656 Much better!

**Comment by AudioTore** [comment]
@Richard5656 Its good!

**Comment by Richard5656** [comment]
Oh thank you. I added some empty functions on top so you could use them instead of calling the usage method inside each item. We could use either one but I prefer usage.

**Comment by Richard5656** [comment]
Instead of our normal 2d would you like to switch to a diffrent method of 2d?

**Comment by Richard5656** [comment]
@AudioTore Like side ways 2d instead of top down. https://th.bing.com/th/id/R.a720c586785cae8927ac3cebde1ea8e0?rik=%2bqWUgEb4O7dtDw&riu=http%3a%2f%2fimages.pushsquare.com%2fscreenshots%2f49127%2flarge.jpg&ehk=nTNIgXdpQLFJIGx%2bXkJRsc%2b0EA6pyBbr%2bRWQEUBn3%2bY%3d&risl=&pid=ImgRaw&r=0

**Comment by Richard5656** [comment]
we dont necesarily need to utilize x and y for this 2d and we can give the player an easier time to explore places with this while building maps easier.

**Comment by Richard5656** [comment]
What do I code for the missions?

**Comment by Richard5656** [comment]
https://github.com/AudioTore/Rthon/compare/main...Richard5656:patch-3
https://github.com/AudioTore/Rthon/compare/main...Richard5656:patch-2

Dont do https://github.com/AudioTore/Rthon/compare/main...Richard5656:patch-1

**Comment by AudioTore** [comment]
@Richard5656 Missions will come later

**Comment by AudioTore** [comment]
What does  print(f"{maine.register_name}'s Inventory:\n\n")
    for i in range(len(inventory)): do?

**Comment by Richard5656** [comment]
"print(f"{maine.register_name}'s Inventory:\n\n")"

Prints player name and inventory using. F strings. Another way to put variables into strings.


"for i in range(len(inventory)): "

This is a for loop done in the style of a person who learned python as a second language. It loops through inventory.

https://www.w3schools.com/python/python_for_loops.asp


www.geeksforgeeks.org/formatted-string-literals-f-strings-python/amp/

**Comment by Richard5656** [comment]
If you don't want me to use loops or f strings I could do that.

**Comment by AudioTore** [comment]
@Richard5656 Try that

**Comment by Richard5656** [comment]
Ok.

**Comment by Richard5656** [comment]
@AudioTore So I'm currently trying to create a algorithm to generate pieces of the map like chunks. And currently I've only been using regular math since I do not fully understand binary math. Anyways most all the algorithms I'm thinking of, I'm not sure you can understand. Is that ok?

**Comment by AudioTore** [comment]
@Richard5656 No. Just use the a4 method of moving.

**Comment by Richard5656** [comment]
I mean like generating the world not movement.

**Comment by AudioTore** [comment]
@Richard5656 No im just gonna make the maps. And when the player goes in a certain direction it just teleports them to the other part of the world

**Comment by Richard5656** [comment]
Oh I see like that.

**Comment by Richard5656** [comment]
@AudioTore Movement will just be teleportation using the y and x axis?

**Comment by AudioTore** [comment]
Yeah

**Comment by Richard5656** [comment]
@AudioTore Intresting.

**Comment by Richard5656** [comment]
@AudioTore So what do you think of this style of 2d? https://th.bing.com/th/id/R.a720c586785cae8927ac3cebde1ea8e0?rik=%2bqWUgEb4O7dtDw&riu=http%3a%2f%2fimages.pushsquare.com%2fscreenshots%2f49127%2flarge.jpg&ehk=nTNIgXdpQLFJIGx%2bXkJRsc%2b0EA6pyBbr%2bRWQEUBn3%2bY%3d&risl=&pid=ImgRaw&r=0

**Comment by AudioTore** [comment]
I was planning to run it in a console

**Comment by Richard5656** [comment]
Yeah we can run that type of 2d in a console with just ascii.

**Comment by Richard5656** [comment]
I was going to suggest it for you because it makes for an easier map making process.

**Comment by AudioTore** [comment]
@Richard5656 Lets try that!

**Comment by Richard5656** [comment]
@AudioTore Yeah lets do it.

**Comment by AudioTore** [comment]
@Richard5656 Alright you work on that movement ima work on the map's

**Comment by AudioTore** [comment]
Ok remade the main menu now im working on the maps. Is there a better way to make maps other than print("""""")

**Comment by Richard5656** [comment]
Just store them in variables. Variable = """""" I need to actually parse them into maps.

**Comment by AudioTore** [comment]
@Richard5656 Ok.

**Comment by Richard5656** [comment]
I hope you have a easier time with this.

**Comment by AudioTore** [comment]
@Richard5656 I got one of the maps ready looks more detailed than the last map

**Comment by AudioTore** [comment]
https://pastebin.com/raw/AQwJn7G5

**Comment by Richard5656** [comment]
It's pretty good. But I'll need to add a few changes to it.

**Comment by AudioTore** [comment]
@Richard5656 Alright

**Comment by Richard5656** [comment]
Would you like me to explain the map parsing process?

**Comment by AudioTore** [comment]
@Richard5656 Sure

**Comment by Richard5656** [comment]
Basically we rewrite the entire map as a 1d array and then rewrite that as a 2d array by using modular arithmetic (division with remainders).

**Comment by Richard5656** [comment]
We can actually do variable[some_number] to access any character in the string but we cannot change it. Oh shoot I just thought of a better way I could convert it directly without wasting time.

**Comment by Richard5656** [comment]
Since I cannot use loops and python doesn't have any other way to loop. I'm going to have to use recursion for all of this.

**Comment by Richard5656** [comment]
Don't worry though it's much more simpler.

**Comment by Richard5656** [comment]
Hey I was wondering if we make maps with this. The A4 teleportation method would be also much more simpiler since we are moving on a sideways view in a line meaning that we are in 1d. The A4 method would work great since we dont have to type in X and Y and we only need to type in X.

**Comment by AudioTore** [comment]
Try it

**Comment by Richard5656** [comment]
Without loops the code will be slightly harder to follow but we should be fine.

**Comment by Richard5656** [comment]
Ok

**Comment by Richard5656** [comment]
Sorry I was working on making the rcursion readable but it should be readable enough now.

**Comment by Richard5656** [comment]
Now ill work on parsing that map

**Comment by Richard5656** [comment]
Pythons not letting me use recurion for the map.

**Comment by Richard5656** [comment]
ok we can just use a simple while loop. https://www.w3schools.com/python/python_while_loops.asp

**Comment by Richard5656** [comment]
Wait nvm its a problem with the code.

**Comment by Richard5656** [comment]
Wait I was right the first time.
![recursion err](https://user-images.githubusercontent.com/80961838/147882542-c4a9e632-6c94-49fe-aa95-f2f83865a3aa.JPG)

**Comment by Richard5656** [comment]
Ill just use a simple while statement. That should be fine.

**Comment by Richard5656** [comment]
https://github.com/AudioTore/Rthon/compare/main...Richard5656:patch-5
https://github.com/AudioTore/Rthon/compare/main...Richard5656:patch-4
Patch 5 is for the maps.
Patch 4 is for the recursion for the inventory and items. 
Ok they are done

**Comment by Richard5656** [comment]
Ok, tell me if the code is understandable.

**Comment by Richard5656** [comment]
So about the miner. Do you want me to generate the mines for the miner. Or would you like to create them? I found a very easy algorithm we could use.

**Comment by Richard5656** [comment]
Ok ive decided to do some math stuff and long story short we now have an easier coordinate system.

**Comment by AudioTore** [comment]
@Richard5656 The code is understandable!

**Comment by Richard5656** [comment]
Yay!!!

**Comment by Richard5656** [comment]
So what now?

**Comment by Richard5656** [comment]
Should I work on the missions or player movement or more maps?

**Comment by Richard5656** [comment]
So I noticeed our maps are only limited to one chracter per brick meaning that you have only used "| / - 0" as building blocks. Would you like to use textures instead?

**Comment by Richard5656** [comment]
We can support 5 by 5 textures as a test first if you would like.

**Comment by Richard5656** [comment]
Since we are working in 1d the textures should be easier to render.

**Comment by AudioTore** [comment]
@Richard5656 Hey sorry. I couldn't respond because i had to go on a trip for a bit.

**Comment by Richard5656** [comment]
@AudioTore it's ok. I looked through my old projects and I found an algorithm for terrain generation. It's very simple. Would you like to implement the algorithm into the game?

**Comment by AudioTore** [comment]
@Richard5656 Sure whats the source code?

**Comment by AudioTore** [comment]
actually nvm i just need maps that's all

**Comment by Richard5656** [comment]
Oh ok. Sorry I was a little busy since winter breaks over. My algorithm can mainly generate only mountains.

**Comment by Richard5656** [comment]
Are we adding a leveling system?

**Comment by AudioTore** [comment]
@Richard5656 To be honest i just want the maps. It's not gonna be like minecraft were the world just generates as you go on.

**Comment by Richard5656** [comment]
Ohh you should've specified that in the beginning, Hold up im in class I'll try to get you the maps later.

**Comment by AudioTore** [comment]
Sorry.

**Comment by Richard5656** [comment]
Hey it's ok the code can still be modified to automatically generate maps that we can use. If you get tired of making the maps we can use this to make some of them. @AudioTore

**Comment by Richard5656** [comment]
The algorithm is just an easier version of the Minecraft generation algorithm.

**Comment by Richard5656** [comment]
@AudioTore So are we making 2 versions of rthon? One for java and one for python?

**Comment by AudioTore** [comment]
@Richard5656 That's the combat that i written for this game that i will later import into the this game

**Comment by Richard5656** [comment]
Oh ok

**Comment by Richard5656** [comment]
Do you need  me to code anything else for the game? @AudioTore

**Comment by AudioTore** [comment]
@Richard5656 Nope i got it! Thank you for helping!

**Comment by AudioTore** [comment]
Just taking a break to avoid burnout

**Comment by Richard5656** [comment]
Oh ok.

**Comment by Richard5656** [comment]
So how many programming languages can you program in?

**Comment by AudioTore** [comment]
I know python, html, css, a little bit of java, little c++,

**Comment by AudioTore** [comment]
im planning to pick java as my main programming language since i like java.

**Comment by Richard5656** [comment]
The programming languages that I program in that aren't machine code,byte code, or assembly and are not a programing language I programed would be C,C++,Java, JavaScript, Python, Html, and Css. Now that I think about this a little more we code in about the same programing languages.

**Comment by Richard5656** [comment]
Html,css, counts as more of styling and not programming in my opinion. I didn't expect you to have this level of how many programming languages you can program in to be this high so fast. You practically know all the high level programming languages I know with the exception of C.

**Comment by AudioTore** [comment]
Yeah html and css isn't really a programming language i should've took that out Mainly because html and css can't be used to make programs.

**Comment by Richard5656** [comment]
You're so young and you know this many already 😮.

**Comment by Richard5656** [comment]
Dude seriously you can actually program nearly anything at this point.

**Comment by AudioTore** [comment]
@Richard5656 Lol I still consider myself as beginner programming as i started this about 2 months ago. Maybe i might program a os But it uses assembly and assembly is kinda painfull to program for me. So im definitely still trying to increase  my programming muscles to get to get better.

**Comment by Richard5656** [comment]
Wait you program in assembly?

**Comment by AudioTore** [comment]
No i don't i tried It was way too hard.

**Comment by Richard5656** [comment]
Learn loops in Java. Then you'll understand.

**Comment by Richard5656** [comment]
The only thing you're really missing is loops and how to count in hexadecimal and binary.

**Comment by Richard5656** [comment]
I can teach you a little X86 Assembly so it'll make sense. I know the tutorials make it sound hard but it's really not that hard. Besides you don't need to understand every aspect of assembly  just enough to get yourself into C++.

**Comment by AudioTore** [comment]
Yeah ima take a little break though to avoid burnout maybe sometime :)

**Comment by Richard5656** [comment]
Oh ok.

**Comment by Richard5656** [comment]
You know if Assembly is to hard to go with you could try Python or Java byte code first and learn up from there.

**Comment by AudioTore** [comment]
Hey we might have to make this game a closed source since i don't want people cheating in the game. Do you have any other way to chat privately and share the source code Since we are the only one's who know's about this project?

**Comment by Richard5656** [comment]
We could try Repl.it but wouldn't people need the python source code to play the game?

**Comment by Richard5656** [comment]
We can just try to obsfucate the code or try to program a anticheat into the game.  @AudioTore

**Comment by Richard5656** [comment]
I was thinking we could ship the code with a C++ encryption/Decryption launcher.

**Comment by AudioTore** [comment]
using pyinstaller we can turn these py files into executable files.

**Comment by AudioTore** [comment]
If we tried to make a anticheat in the game people can just remove it from the source.

**Comment by Richard5656** [comment]
pyinstaller works only on windows right?

**Comment by Richard5656** [comment]
We have ways of making anticheat more permanant. We dont even need to write it into the source code.

**Comment by Richard5656** [comment]
Since we currently working with single player it shouldn't be to much of an issue to continue talking here. But when multiplayer comes we can figure it out then.

**Comment by AudioTore** [comment]
@Richard5656 Actually singleplayer is gonna use coins and coins is a int variable

**Comment by Richard5656** [comment]
Oh I see the problem yeah we could just use pyinstaller for that.

**Comment by Richard5656** [comment]
We can try Repl.it if you want to chat and code.

**Comment by Richard5656** [comment]
Or we could exchange RSA keys and we can encrypt the source code like that.

**Comment by Richard5656** [comment]
There's really no way to 100% stop people from cheating in single player. I mean if we add saves into the game that adds an extra layer of complexity.

**Comment by Richard5656** [comment]
We could attempt to program servers to handle stuff like this but I don't see how we can make it 100% uncheatable.

**Comment by AudioTore** [comment]
I signed up on replit.com

**Comment by Richard5656** [comment]
oh ok would you like to link your github so we can program in the python files?

**Comment by AudioTore** [comment]
@Richard5656 Yeah i just did

**Comment by Richard5656** [comment]
Ok send me a invite to the project. Im @Richard565

**Comment by AudioTore** [comment]
On replit or github?

**Comment by Richard5656** [comment]
On repl.it. im \@Richard565

**Comment by Richard5656** [comment]
Its not letting me send the @ .

**Comment by AudioTore** [comment]
i invited you

**Comment by Richard5656** [comment]
Yeah im in

**Comment by Richard5656** [comment]
can you put the files into the group?

**Comment by AudioTore** [comment]
Java or python?

**Comment by Richard5656** [comment]
Just all that go with this game.

**Comment by AudioTore** [comment]
Ok i added the file

**Comment by Richard5656** [comment]
Ok I'm in

**Comment by AudioTore** [comment]
Alright so how do we talk on replit?

**Comment by Richard5656** [comment]
click the chat icon

**Comment by AudioTore** [comment]
Ima close this

**Comment by Richard5656** [comment]
ok
